[2025-01-19T20:36:52.164+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_md_currency_d scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:01.687+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_md_currency_d scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:01.689+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:01.784+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_md_currency_d> on 2025-01-18 00:00:00+00:00
[2025-01-19T20:37:01.876+0000] {standard_task_runner.py:60} INFO - Started process 162 to run task
[2025-01-19T20:37:01.937+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_md_currency_d', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp0ze5tqoe']
[2025-01-19T20:37:01.965+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask load_md_currency_d
[2025-01-19T20:37:03.880+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_md_currency_d scheduled__2025-01-18T00:00:00+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:04.199+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_md_currency_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-01-19T20:37:04.363+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:06.254+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:07.293+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('md_currency_d', 'tmp_md_currency_d');
    , parameters: None
[2025-01-19T20:37:07.364+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:12.443+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:12.592+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for md_currency_d', datetime.datetime(2025, 1, 19, 20, 37, 4, 204540), datetime.datetime(2025, 1, 19, 20, 37, 12, 372840), 'Completed', 50, '50 rows affected.')
[2025-01-19T20:37:12.607+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:12.626+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:13.070+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_md_currency_d;, parameters: None
[2025-01-19T20:37:13.134+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:13.242+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_md_currency_d, execution_date=20250118T000000, start_date=20250119T203652, end_date=20250119T203713
[2025-01-19T20:37:13.466+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:13.609+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
