[2025-01-19T20:36:52.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_md_currency_d manual__2025-01-19T20:36:31.680662+00:00 [queued]>
[2025-01-19T20:37:11.822+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_md_currency_d manual__2025-01-19T20:36:31.680662+00:00 [queued]>
[2025-01-19T20:37:11.832+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:17.634+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_md_currency_d> on 2025-01-19 20:36:31.680662+00:00
[2025-01-19T20:37:17.684+0000] {standard_task_runner.py:60} INFO - Started process 174 to run task
[2025-01-19T20:37:17.716+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_md_currency_d', 'manual__2025-01-19T20:36:31.680662+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpn1c2cee1']
[2025-01-19T20:37:17.730+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask load_md_currency_d
[2025-01-19T20:37:18.070+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_md_currency_d manual__2025-01-19T20:36:31.680662+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:18.598+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_md_currency_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T20:36:31.680662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-19T20:36:31.680662+00:00'
[2025-01-19T20:37:18.782+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:19.200+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:19.369+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('md_currency_d', 'tmp_md_currency_d');
    , parameters: None
[2025-01-19T20:37:19.388+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:24.465+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:24.691+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for md_currency_d', datetime.datetime(2025, 1, 19, 20, 37, 18, 608371), datetime.datetime(2025, 1, 19, 20, 37, 24, 403533), 'Completed', 50, '50 rows affected.')
[2025-01-19T20:37:24.700+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:24.736+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:24.896+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_md_currency_d;, parameters: None
[2025-01-19T20:37:24.933+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:24.981+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_md_currency_d, execution_date=20250119T203631, start_date=20250119T203652, end_date=20250119T203724
[2025-01-19T20:37:25.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:25.403+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
